package inheritance;

// The implied super() call in B’s constructor cannot be 
// satisfied because there isn’t a no-arg constructor in A. 
// A default, no-arg constructor is generated by the compiler 
// only if the class has no constructor defined explicitly
class ParentConstructorArguments {
	public ParentConstructorArguments(String s) {
		System.out.print("A");
	}
}

public class ConstructorArguments extends ParentConstructorArguments {
	public ConstructorArguments(String s) {
		super(s); //Necessary, because no default constructor
		System.out.print("B");
	}

	public static void main(String[] args) {
		new ConstructorArguments("C");
		System.out.println(" ");
	}
}